services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trainingdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password

volumes:
  postgres-data: 